apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-k8s-config
  labels:
      app: spring-boot-k8s-config
data:
  spring-boot-k8s-config.yml: |
    server:
      servlet:
        contextPath: /spring-k8s
    target:
      application: spring-k8s
      description: Testing kubernetes deployment,service,configMap,secret,ingress.