apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-k8s.fullname" . }}-secret
  labels:
      app: {{ include "spring-boot-k8s.fullname" . }}-secret
type: Opaque
data:
    {{ .Values.volumeMounts.serectSubPath }}: bXlzcWw6CiAgdXNlcm5hbWU6IHJvb3QKICBwYXNzd29yZDogMTIzNDU2