apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-k8s.fullname" . }}-service
  labels:
    name: {{ include "spring-boot-k8s.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.appServer.port }}
  selector:
    app: {{ include "spring-boot-k8s.fullname" . }}